### ISSUE TITLE
cas_native

### ISSUE THREAD

**Issue by gokhandincer** [lightbend/reactive-lib#100]
Hi everyone,

I generated deployment file with **rp generate-kubernetes-resources** and applied to java options for cassandra connection like below

```
-Dcom.lightbend.platform-tooling.service-discovery.external-service-addresses.cas_native.0=cassandra.default.svc.cluster.local
```

but I got error like this:

```
2018-12-13 20:14:26,599 [ERROR] a.a.OneForOneStrategy - requirement failed: missing port in //100.96.1.53 for Cassandra contact points cas_native
java.lang.IllegalArgumentException: requirement failed: missing port in //100.96.1.53 for Cassandra contact points cas_native
```

How to resolve this issue. Thanks

**Comment by TimMoore** [comment]
This is expecting an SRV style hostname, with the port name and protocol.

See https://discuss.lightbend.com/t/access-cassandra-on-kubernetes/2847/2?u=timmoore

**Comment by gokhandincer** [comment]
Thank you @TimMoore
