### ISSUE TITLE
Support for Akka Discovery

### ISSUE THREAD

**Issue by renatocaval** [lightbend/reactive-lib#101]
We should have support for Akka Discovery (available in Akka 2.5.19)

When doing that, we should replace the Lagom ServiceLocator by the new one we are developing here: https://github.com/lagom/service-locator-akka-discovery

And we must upgrade to upcoming akka-management 0.50.

Depends on https://github.com/lagom/service-locator-akka-discovery/issues/9
Depends on #96 
Relates to https://github.com/akka/akka-management/issues/419

**Comment by patriknw** [comment]
This means removing (replacing) `reactive-lib-service-discovery`, `reactive-lib-service-discovery-lagom14-java`, `reactive-lib-service-discovery-lagom14-scala`

**Comment by renatocaval** [comment]
I would say, removing. 

In principle, the goal for 2.0.0 is to support Lagom 1.5.0. 

Lagom 1.4.x users should stay with previous version, unless we it proves to be feasible easy. 

That said, in 2.0.0, we can remove all of this and replace by https://github.com/lagom/service-locator-akka-discovery

**Comment by TimMoore** [comment]
It doesn't sound like we need to remove anything from `reactive-lib`, but rather we should make version 2.0 of `sbt-reactive-app` bring in `service-locator-akka-discovery` and other new modules instead of `reactive-lib`. Correct?

**Comment by renatocaval** [comment]
I would even prefer `sbt-reactive-app` to do nothing related to dependency management.

If I add the `service-locator`, `play-cluster-bootstrap` and `akka-management`, what else should I need to add?

Or am I missing something?

**Comment by TimMoore** [comment]
Lightbend Orchestration is no longer actively developed and will reach its [End of Life](https://developer.lightbend.com/docs/lightbend-platform/2.0/support-terminology/index.html#end-of-life-eol-) on April 15, 2020.

We recommend [Migrating to the Improved Kubernetes Deployment Experience](https://developer.lightbend.com/docs/lightbend-orchestration/current/migration.html).
