### ISSUE TITLE
Remove ApplicationStatus

### ISSUE THREAD

**Issue by patriknw** [lightbend/reactive-lib#108]
When updating to Akka Management 1.0.0 the health checks are implemented via https://github.com/akka/akka-management/issues/402

**Comment by TimMoore** [comment]
If this is going to change the paths, please be sure to document this in the release notes or a migration guide.

**Comment by patriknw** [comment]
ok, I created issue https://github.com/lightbend/reactive-lib/issues/110 for collecting notes for migration guide.

**Comment by TimMoore** [comment]
Lightbend Orchestration is no longer actively developed and will reach its [End of Life](https://developer.lightbend.com/docs/lightbend-platform/2.0/support-terminology/index.html#end-of-life-eol-) on April 15, 2020.

We recommend [Migrating to the Improved Kubernetes Deployment Experience](https://developer.lightbend.com/docs/lightbend-orchestration/current/migration.html).
