### ISSUE TITLE
Migration guide from 1.x

### ISSUE THREAD

**Issue by patriknw** [lightbend/reactive-lib#110]

**Comment by patriknw** [comment]
ApplicationStatus removed and health check URLs changed, see #108

**Comment by patriknw** [comment]
@eed3si9n @TimMoore @chbatey I have created Milestone 2.0.0-RC1, which will be using Akka Management 1.0.0 and Akka 2.5.19 (for Lagom 1.5).

I assume 2.0.0 is the version number we are going to use, because of the breaking changes?

**Comment by patriknw** [comment]
I have looked deeper at the code in `reactive-lib` and created tickets with [2.0.0-RC1 milestone](https://github.com/lightbend/reactive-lib/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.0.0-RC1)

I must be missing something because if we do those I see nothing remaining apart from a few rp-tooling.conf that are setting config properties from environment variables for address/port.

**Comment by ignasi35** [comment]
> I must be missing something because if we do those I see nothing remaining apart from a few rp-tooling.conf that are setting config properties from environment variables for address/port.

I think your assessment is correct. I'd like @renatocaval's opinion though.

**Comment by eed3si9n** [comment]
Would it be too ambitious to aim for Migration guide for 1.6 -> 1.7 -> 🔥?
As in release 1.7 against 0.20.0 that deprecates some unwanted features like auto port mapping, secrets, etc, and then aim to drop reactive-lib entirely and switch to Akka Management 1.0.0.

**Comment by patriknw** [comment]
I have confirmed with @TimMoore and @jroper that we shouldn't have a 2.0. The 1.x series will be maintained for Lagom 1.4 users. For Lagom 1.5 users and others we should focus on migration guide for using plain Akka Management and the new Play/Lagom modules for service locator and bootstrap auto-start.

**Comment by patriknw** [comment]
The migration guide will live in the Lagom documentation.
I renamed the milestone here to [retire](https://github.com/lightbend/reactive-lib/issues?utf8=✓&q=is%3Aopen+is%3Aissue+milestone%3Aretire)

**Comment by TimMoore** [comment]
In addition to the migration guide, we'll have to have deployment documentation for new users in Lagom. Right now, the Lightbend Orchestration documentation is the closest thing we have. @marcospereira, @jroper, @eed3si9n please coordinate on how and when this can be done.

**Comment by TimMoore** [comment]
Done: [Migrating to the Improved Kubernetes Deployment Experience](https://developer.lightbend.com/docs/lightbend-orchestration/current/migration.html).
