### ISSUE TITLE
Move ClusterBootstrapAutostart?

### ISSUE THREAD

**Issue by patriknw** [lightbend/reactive-lib#111]
Should it move to a Lagom module?

Also discussed in https://github.com/akka/akka-management/issues/303, but that might be obsolete?

**Comment by patriknw** [comment]
Similar question for `AkkaManagementAutostart`.

For Lagom I guess there is no real need for only enabling AkkaManagement without ClusterBootstrap so it might not be needed and both can be enabled by ClusterBootstrapAutostart?

**Comment by ignasi35** [comment]
I think [@ktoso's point](https://github.com/akka/akka-management/issues/303#issuecomment-422290694) about allowing users (or lagom as a framework) to do some initial setup before `.start()` is still valid.

> Should it move to a Lagom module?

About the new location for `AkkaManagementAutostart` and `ClusterBootstrapAutostart` I'm not very sure. Play users eventually will want to use `AkkaManagement` on their deployments or build a  cluster. I guess we can hold it under the Lagom org and make it so Play users can pick it up.

+1 to moving to Lagom.

**Comment by renatocaval** [comment]
The goal is to have `play-cluster-bootstrap` module. This should be similar to current Lagom cluster formation for dev-mode and use Akka Cluster Bootstrap in Prod.

I don't think this should be in 2.0.0. Unless we have a strong reason for it. 

If current reactive-lib bootstrap works with Lagom 1.5.0, then we should stick with it for now and replace it with `play-cluster-bootstrap` on a future release.

**Comment by patriknw** [comment]
The reason could be that there is nothing remaining in reactive-lib so we would not need to release and maintain 2.0 at all.

**Comment by TimMoore** [comment]
I think the timing will have to depend on who is doing it, but I agree with @renatocaval that this should target Play generically, and not Lagom specifically.

Regarding users doing some other setup code before calling `start()`, I think it's not such a problem as long as this is opt-in. If someone has more complex setup, they can just not use the auto-start module and start manually from their custom setup module. For this to work, it's important that nothing else is coupled into the same module.

For `lagom.cluster.exit-jvm-when-system-terminated`, I wonder if it would be better to make this default to `on` in Lagom and then override to `off` only in development mode. Wouldn't most users want it `on`? The `join-self` property already defaults to `off`, so I don't know why that was in there.

**Comment by TimMoore** [comment]
This is now part of Lagom 1.5.0. A generic Play module may come in the future.
