### ISSUE TITLE
Add Artery properties to rp-tooling.conf

### ISSUE THREAD

**Issue by patriknw** [lightbend/reactive-lib#112]
reactive-lib/akka-cluster-bootstrap/src/main/resources/rp-tooling.conf contains
```
  remote {
    netty.tcp {
      hostname = ${?RP_ENDPOINT_AKKA_REMOTE_HOST}
      port = ${?RP_ENDPOINT_AKKA_REMOTE_PORT}

      bind-hostname = ${?RP_ENDPOINT_AKKA_REMOTE_BIND_HOST}
      bind-port = ${?RP_ENDPOINT_AKKA_REMOTE_BIND_PORT}
    }
  }
```

It should also include corresponding properties for Artery.

**Comment by TimMoore** [comment]
Lightbend Orchestration is no longer actively developed and will reach its [End of Life](https://developer.lightbend.com/docs/lightbend-platform/2.0/support-terminology/index.html#end-of-life-eol-) on April 15, 2020.

We recommend [Migrating to the Improved Kubernetes Deployment Experience](https://developer.lightbend.com/docs/lightbend-orchestration/current/migration.html).
