### ISSUE TITLE
lagomUnmanagedServices does not work

### ISSUE THREAD

**Issue by Simiil** [lightbend/reactive-lib#123]
I'm not sure where to put this issue exactly.

I'm using the lagomUnmanagedServices property in the build.sbt to bind a service to an external rest endpoint (like `https://service.com/api/v3/`). This works fine locally:

    lagomUnmanagedServices in ThisBuild := Map(
      "externalService" -> "https://service.com/api/v3/"
    )

after deploying to a kubernetes cluster using the orchestration tool, the lookup to that service fails:

    java.lang.IllegalStateException: Service externalService was not found by service locator

I am reasonably sure that this worked before upgrading the reactive-app to 1.7

**Comment by ihostage** [comment]
`lagomUnmanagedServices` used only for Dev-mode.
For production, you need to use key `--external-service`. See [documentation](https://developer.lightbend.com/docs/lightbend-orchestration/current/features/service-location.html#external-services)
Or create K8S Service with Endpoints. You can see example in this discussion https://discuss.lightbend.com/t/access-cassandra-on-kubernetes/2847/5
