### ISSUE TITLE
Document the settings in rp-tooling.conf

### ISSUE THREAD

**Issue by fsat** [lightbend/reactive-lib#22]
We need to document the settings we have in [rp-tooling.conf](https://github.com/lightbend/reactive-lib/pull/21/files#diff-9306c669e04b3ddf3e8bda5cdaa341de).

We will need to document how the environment variables such as `RP_ENDPOINT_AKKA_MGMT_HTTP_BIND_HOST` will be supplied.

We may also need to document the reason why a certain value is set (if applicable, for example why `resolve-interval` is `1 second`).

This issue is raised in relation to #21 PR.

**Comment by TimMoore** [comment]
Lightbend Orchestration is no longer actively developed and will reach its [End of Life](https://developer.lightbend.com/docs/lightbend-platform/2.0/support-terminology/index.html#end-of-life-eol-) on April 15, 2020.

We recommend [Migrating to the Improved Kubernetes Deployment Experience](https://developer.lightbend.com/docs/lightbend-orchestration/current/migration.html).
