### ISSUE TITLE
Enable ConfigMaps

### ISSUE THREAD

**Issue by dsugden** [lightbend/reactive-lib#51]
In the same way that secrets can be created and accessed:

 kubectl create secret <...> --from-file=<...>

SecretReader.get(name, key)

Do the same for ConfigMaps:

https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/

**Comment by emanueloliveira23** [comment]
Hi, 

@dsugden, seeing the source code, more precisely at [Annotations.scala](https://github.com/lightbend/reactive-cli/blob/a4b0a24ad2269e6dda55b7af4ebda81c062a86f1/cli/shared/src/main/scala/com/lightbend/rp/reactivecli/annotations/Annotations.scala), I discovery the using the following model should works in CLI:

```bash
# ...
--env com.lightbend.rp.environment-variables.<n>.type=kubernetes.configMap
--env com.lightbend.rp.environment-variables.<n>.name=<ENV NAME>
--env com.lightbend.rp.environment-variables.<n>.map-name=<CONFIGMAP NAME>
--env com.lightbend.rp.environment-variables.<n>.key=<CONFIGMAP KEY> 
# ...
```
* `<ENV NAME>` is the name of environment variable.
* `<CONFIGMAP NAME>` is the name of configmap.
* `<CONFIGMAP KEY>` is the key property in configmap.
* `<n>` seems to be the identifier of environment variable and can be any positive integer (you should give)

**Comment by TimMoore** [comment]
It's simpler to access config maps using the normal Kubernetes support for environment variables and volumes. We aren't planning to implement this.

**Comment by eed3si9n** [comment]
```scala
environmentVariables := Map(
  "MY_VAR" -> kubernetes.ConfigMapEnvironmentVariable("my-map", "my-key"))
```

The above will generate MY_VAR with configMapKeyRef to my-map.

```yaml
            - name: "MY_VAR"
              valueFrom:
                configMapKeyRef:
                  name: "my-map"
                  key: "my-key"
```
