### ISSUE TITLE
Retry DNS lookups

### ISSUE THREAD

**Issue by longshorej** [lightbend/reactive-lib#53]
Since DNS is over UDP, should we retry DNS lookups with some sort of backoff? [akka-dns](https://github.com/ilya-epifanov/akka-dns) itself doesn't retry anything AFAIK.

**Comment by ktoso** [comment]
It doesn't retry; not sure DNS clients abstract this usually; If you think it's required better to fix in Akka perhaps

**Comment by longshorej** [comment]
I think most OS impls for DNS do retry. That linked .ru DNS project which we're depending on for DNS SRV doesn't though; it's re-implementing DNS and not relying on the OS subsystems.

Perhaps this comes back to the best solution be that Akka be able to do DNS SRV, thus removing any need to use that lib in the first place.

**Comment by ktoso** [comment]
Yeah, that would be good... We can talk about timing of implementing that perhaps

**Comment by ktoso** [comment]
cc @patriknw

**Comment by alanngai** [comment]
@ktoso, @patriknw, should we create a ticket on the akka side and close this one?  Would it be [akka-management](https://github.com/akka/akka-management) or somewhere else?

**Comment by longshorej** [comment]
This was implemented in https://github.com/lightbend/reactive-lib/pull/55 - something similar will probably need to be done in Akka Management depending upon where the code ultimately lives.

**Comment by ktoso** [comment]
What are we talking about here? Is it for cluster bootstraping or in general in the dns impl in akka (note that the linked "akka-dns" is not our project and we do not maintain it).

**Comment by longshorej** [comment]
This is for the service locator in reactive-lib that uses akka-dns (i.e. that .ru project). I'd guess this issue can be closed as it's taken care of here. In akka-management it's only a problem if you're going to use that lib (which I don't think you're planning to do..)
