### ISSUE TITLE
document usage for other libs

### ISSUE THREAD

**Issue by dbrinegar** [lightbend/reactive-lib#56]
We show how to use with sbt-reactive-app but not how to include in other libs.  Write an example in README for libs.

**Comment by TimMoore** [comment]
Lightbend Orchestration is no longer actively developed and will reach its [End of Life](https://developer.lightbend.com/docs/lightbend-platform/2.0/support-terminology/index.html#end-of-life-eol-) on April 15, 2020.

We recommend [Migrating to the Improved Kubernetes Deployment Experience](https://developer.lightbend.com/docs/lightbend-orchestration/current/migration.html).
