### ISSUE TITLE
debug logs for dns search

### ISSUE THREAD

**Issue by dbrinegar** [lightbend/reactive-lib#64]
doLookup() has some fairly complex dns search behavior.  It would be nice to have debug logs for the full names being assembled, and for lookup failures.

https://github.com/lightbend/reactive-lib/blob/master/service-discovery/src/main/scala/com/lightbend/rp/servicediscovery/scaladsl/ServiceLocator.scala#L219

**Comment by alanngai** [comment]
service location is due for a consolidation (between reactive-lib, lagom, and akka).  May want to see what direction that goes in before deciding this

**Comment by TimMoore** [comment]
We'll handle this within Akka/Akka Management.
