### ISSUE TITLE
rp-tool generated healtcheck failed in mesosphere, had to revert to curl one

### ISSUE THREAD

**Issue by ktoso** [lightbend/reactive-lib#69]
I'll try to figure out what version of mesos this was.. but it seemed to fail with the http requests being invalid -- not including the host header AFAIR...

Would love to have more detailed info but don't have access to the env currently.

**Comment by alanngai** [comment]
closing as duplicate of lightbend/reactive-cli#162

**Comment by ktoso** [comment]
Ah wrong repo, thanks Alan
