### ISSUE TITLE
ClusterStatusCheck should report as healthy during bootstrap

### ISSUE THREAD

**Issue by patrick-premont** [lightbend/reactive-lib#71]
Restarts during bootstrapping will tend to prevent it from completing successfully. Due to the currently perceived unhealthy status of bootstrapping nodes, we may see such restarts.

Replaces akka/akka-management#259

**Comment by dwijnand** [comment]
Doesn't look like this is using milestones, but I'd say we should ship this in a 0.10.0.

**Comment by ktoso** [comment]
Okey, so from now on let's use milestones :-)
Makes understanding what we release easier...

**Comment by chbatey** [comment]
Is 0.10.0 the right version? This looks to have been in a released version but 0.10.0 hasn't been released

**Comment by TimMoore** [comment]
Looks like it was released in 0.9.1.
