### ISSUE TITLE
Update Akka Management to 0.18.0

### ISSUE THREAD

**Issue by TimMoore** [lightbend/reactive-lib#81]
https://github.com/akka/akka-management/releases/tag/v0.18.0

**Comment by alanngai** [comment]
relevant links
- https://developer.lightbend.com/docs/akka-management/0.18.0/bootstrap/index.html
- https://developer.lightbend.com/docs/akka-management/current/bootstrap/recipes.html

specifically, reactivelib's ability to use akka management should also now support dns service discovery.  Given that not all k8s clusters have the prerequisite ability to support the [publishNotReadyAddresses](https://kubernetes.io/docs/reference/federation/v1/definitions/#_v1_servicespec) reactivelib also needs to support bootstrapping with both kubernetes-api and akka-dns

**Comment by eed3si9n** [comment]
https://github.com/lightbend/reactive-lib/pull/82 fixes the bump to Akka Management 0.18.0.

I will address the ability to use DNS service discovery in a separate PR by removing the hard-coding to the built-in one, which would be a breaking change.

**Comment by TimMoore** [comment]
@alanngai this library already includes its own set of pre-defined health check routes

**Comment by TimMoore** [comment]
Let's hold off from any changes to the discovery mechanism for now, until we have a better understanding of what the dependencies are.
