### ISSUE TITLE
Remove the reactive-lib Akka Discovery method

### ISSUE THREAD

**Issue by TimMoore** [lightbend/reactive-lib#83]
The `akka-cluster-bootstrap` module defines a new Akka Discovery method:

https://github.com/lightbend/reactive-lib/blob/13e8f9c56c9841e650ffb562dbefa046b3ebb5bd/akka-cluster-bootstrap/src/main/resources/rp-tooling.conf#L10-L16

This uses the built-in `ServiceLocator` provided by `reactive-lib`, however `reactive-cli` always overrides this value with another one in the generated YAML:

https://github.com/lightbend/reactive-cli/blob/a4b0a24ad2269e6dda55b7af4ebda81c062a86f1/cli/shared/src/main/scala/com/lightbend/rp/reactivecli/runtime/kubernetes/PodTemplate.scala#L74-L92

https://github.com/lightbend/reactive-cli/blob/08addd9d3fd431fa5eb05f23c8948a8f87b57366/cli/shared/src/main/scala/com/lightbend/rp/reactivecli/runtime/marathon/RpEnvironmentVariables.scala#L54-L66

It appears that `ClusterServiceDiscovery` is never actually used in practice, so let's delete it.

This will need to be tested with real example projects (such as Lagom's Chirper and Online Auction examples) and real Kubernetes clusters (such as Minikube and OpenShift).

**Comment by TimMoore** [comment]
Since we're not positive that this is never used, and it isn't causing any harm, we'll leave it as is.

**Comment by TimMoore** [comment]
Reopening, since the Akka Discovery API is changing (as it moves into Akka Core).

**Comment by eed3si9n** [comment]
Confirmed using Online Auction + locally built https://github.com/lightbend/reactive-lib/pull/99

<img width="613" alt="old_chair" src="https://user-images.githubusercontent.com/184683/50729601-cf7e0b00-110a-11e9-8295-33ea0ca0d313.png">
