### ISSUE TITLE
LagomServiceLocator: configurable portname

### ISSUE THREAD

**Issue by thomschke** [lightbend/reactive-lib#87]
- At the moment LagomServiceLocator has a fixed portname "**http**".
https://github.com/lightbend/reactive-lib/blob/36f34d67a21293f35fdccd09b110f28cb6930c69/service-discovery-lagom14-scala/src/main/scala/com/lightbend/rp/servicediscovery/lagom/scaladsl/LagomServiceLocator.scala#L31
###
- [Istio](istio.io) requires [portnaming convention for k8s-services](https://istio.io/help/faq/traffic-management/#naming-port-convention). 

- Due to Lagom 1.4.x use [Akka HTTP](https://www.playframework.com/documentation/2.6.x/AkkaHttpServer) as server engine with HTTP/2 support, the portname for lagom services should named "**http2**".

**Comment by TimMoore** [comment]
Thanks for reporting, @thomschke. Can you send a pull request to make this configurable?

**Comment by TimMoore** [comment]
@thomschke also note that Lagom does not use HTTP/2 by default.

Is this actually not working for you, or a hypothetical problem?

**Comment by thomschke** [comment]
You are right. HTTP/2 support is a big topic. There are a lot of more sideeffects in related projects such as `akka/akka-management`, `lightbend/reactive-lib`, `lightbend/sbt-reactive-app` and so on ... that's why I will close this issue.

If you do the step in the future, please name all service-ports with the prefix `'http2-'` to comply with the [portnaming convention of istio](https://istio.io/help/faq/traffic-management/#naming-port-convention).
