### ISSUE TITLE
Akka 2.5.19

### ISSUE THREAD

**Issue by eed3si9n** [lightbend/reactive-lib#96]
Akka 2.5.19 moves the discovery, so we probably should wait on bumping this.

https://github.com/lightbend/reactive-lib/pull/90/commits/bd3b47dc9464c789798ace9a55a3e0db5802388e

**Comment by eed3si9n** [comment]
Probably goes hand in hand with https://github.com/lightbend/reactive-lib/issues/93.

**Comment by TimMoore** [comment]
Seems like this could be done in 1.6.x, right? Lagom 1.4.10 already depends on Akka 2.5.19.

**Comment by eed3si9n** [comment]
Next reactive-lib I'm planning is 1.7.0, so we can attempt the bump then.

**Comment by eed3si9n** [comment]
Fixed in #116
